version: '3'

services:
  wordpress:
    image: your-wordpress-image # Use the image built from the Dockerfile
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your_db_user
      WORDPRESS_DB_PASSWORD: your_db_password
      WORDPRESS_DB_NAME: your_db_name
    depends_on:
      - db
    networks:
      - wp-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  db-data:
